name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics-3d-contrib: # Renamed job for 3D contrib
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Added checkout step for git operations
      - name: 3D Isometric Calendar
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A .
          git commit -m "generated"
          git push

  github-metrics-stats: # New job for General Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: General Stats
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: JhiNResH
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Taipei
          repositories_forks: yes
          plugin_languages: yes
          plugin_languages_ignored: >-
            tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_threshold: 0%
          plugin_languages_limit: 8
          plugin_achievements: yes
          plugin_achievements_display: compact

      - name: Terminal Style Stats
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.terminal.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: JhiNResH
          template: terminal
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Taipei
          repositories_forks: yes
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_ignored: >-
            tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_threshold: 0%
